In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел.
a=np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
# Создать 5 двумерных массивов разной формы из массива a.
# Не использовать в аргументах метода reshape число -1.
a1=a.reshape(2, 6)
a2=a.reshape(3, 4)
a3=a.reshape(6, 2)
a4=a.reshape(4, 3)
a5=a.reshape(12, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [4]:
# Создать 5 двумерных массивов разной формы из массива a.
# Использовать в аргументах метода reshape число -1
a1=a.reshape(2, -1)
a2=a.reshape(3, -1)
a3=a.reshape(-1, 2)
a4=a.reshape(-1, 3)
a5=a.reshape(12, -1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)


[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [5]:
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
# в отличии от одномерного, указанный массив имеет номер строки 
#и номер столбца, выводится как двумерный массив с дополнительными [].

In [6]:
# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой
b=np.random.randn(3,4)
b

array([[-0.03301739,  0.22717445, -1.32290115, -1.11404358],
       [-0.18896316, -0.49226926, -0.76185141,  1.23591989],
       [ 0.71668848,  0.18340538,  1.8629512 , -0.79192649]])

In [7]:
# Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный.
print(b.size)
b=b.flatten()
print(b.size)
b

12
12


array([-0.03301739,  0.22717445, -1.32290115, -1.11404358, -0.18896316,
       -0.49226926, -0.76185141,  1.23591989,  0.71668848,  0.18340538,
        1.8629512 , -0.79192649])

In [8]:
# Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно.
a=np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [9]:
# Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1.
b=np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [10]:
# В чем разница между массивами a и b?
# Массив a - одномерный, а  массив b - двумерный

In [17]:
# Вертикально соединить массивы a и b.
a = np.zeros((2, 2))
print(a)
b = np.zeros((3, 2))+1
print(b)
v = np.vstack((a, b))
print(v)
print(a.shape, b.shape, v.shape)
v.size

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
(2, 2) (3, 2) (5, 2)


10

In [18]:
# Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
a=np.arange(0, 12)
print(a)
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy).
A=a.reshape(4,3)
print(A)
# Получить матрицу At путем транспонирования матрицы A. 
At=A.T
print(At)
# Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
B = np.dot(A, At)
print(B)
B.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


(4, 4)

In [19]:
# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. 
np.random.seed(42)

In [23]:
# Создайте одномерный массив c, составленный из последовательности 16-ти случайных чисел.
c=np.random.randint(0, 16,16)
print(c)
# Поменяйте его форму так, чтобы получилась квадратная матрица C.
C=c.reshape(4,4)
print(C)
# Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C.
D=B+C*10
print(D)
d=np.linalg.det(D)
print('Определитель - ', d)
r=np.linalg.matrix_rank(D)
print('Ранг - ', r)
# Вычислите обратную матрицу D_inv для D.
D_inv=np.linalg.inv(D)
D_inv

[ 3  7  7  2  5  4  1  7 11 13  5  1 15 11  4  0]
[[ 3  7  7  2]
 [ 5  4  1  7]
 [11 13  5  1]
 [15 11  4  0]]
[[ 35  84  93  52]
 [ 64  90  96 192]
 [133 216 199 222]
 [182 232 252 302]]
Определитель -  -23404999.999999978
Ранг -  4


array([[-0.02745824, -0.02127921, -0.00030506,  0.01848067],
       [-0.00983038, -0.00115445,  0.03006537, -0.01967443],
       [ 0.03091391,  0.00259603, -0.0266755 ,  0.01263576],
       [-0.00169622,  0.01154454, -0.00065371, -0.00325571]])

In [21]:
# Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные — к единице. 
D_inv=np.where(D_inv<0, 0,1)
print(D_inv)
print(B)
print(C)
# Получите матрицу E размером 4x4, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных.
E=np.where(D_inv==1, B, C)
E

[[1 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 1 0]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])